version: '3.8'

services:
  cerb-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cerb-frontend:dev
    container_name: cerb-frontend
    ports:
      - 3000:0000
    environment:
      - VITE_API_URL="http://localhost:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "run", "dev"]
  cerb-backend:
    build:
      context: ../cerberus-wcl-backend
      dockerfile: Dockerfile
      