version: '3.8'

services:
 vue-dev:
  platform: linux/amd64
  build:
   context: .
  tty: true
  environment:
    - CHOKIDAR_USEPOLLING=true
  ports:
    - 8080:8080
  volumes:
    # - ./src:/app/src
    - ./:/app
  # command: [ "http-server", "dist" ]
  command: [ "npm" , "run", "dev", "--host" ]