version: '3.8'

services:
 vue-dev:
  build:
   context: .
  tty: true
  environment:
    - CHOKIDAR_USEPOLLING=true
  ports:
    - 3000:3000
  volumes:
    - ./:/app
    - /app/node_modules # <- Required so that the host node_modules directory doesn't conflict with what is in the container
  command: [ "npm" , "run", "dev", "--host" ]